### ISSUE TITLE
Update project

### ISSUE THREAD

**Issue by Fantomas42** [django-blog-zinnia/zinnia-threaded-comments#4]
https://github.com/Fantomas42/django-blog-zinnia/issues/473

**Comment by azaghal** [comment]
Are you still interested in having this application functioning? I have been doing some rough quick-patching for it while updating the migration app for Drupal 6, and seems it would be fairly easy to get it going, except for migrations (since the app currently uses south).

**Comment by Fantomas42** [comment]
Project updated and published on Pypi under v0.4
