### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by reidelon** [django-blog-zinnia/zinnia-threaded-comments#6]
Currently I trying to create a new comment and I have the zinnia-threaded-comments installed and I get the an error, without this app I have not any error, you can download the project in this URL https://github.com/reidelon/zinnia-threaded-comments.git

**Error during template rendering**

In template /root/projects/myenv3.6/lib/python3.6/site-packages/zinnia/templates/zinnia/skeleton.html, error at line 11

**'Comment' object has no attribute '_mptt_meta'**

 this is the line 11:

 `<meta name="keywords" content="{% block meta-keywords %}django, blog, weblog, zinnia{% endblock meta-keywords %}" />`

# Expected behavior
to add a new comment to this entry

# Steps to reproduce the issue

  1. Create an Entry.
  2. Make a new comment.

# Specifications

 - Zinnia version: 0.18.1
 - Django version: 1.11.3
 - Python version:3.6
 - Operating system:debian x86
 - In the root of the project it is the requirements.txt

**Comment by Fantomas42** [comment]
Hello,

    COMMENTS_APP = 'zinnia_threaded_comments'

is missing in your settings.

Regards

**Comment by reidelon** [comment]
thanks Julian it was a dumber mistake But I think It is no too clear
that configuration in the doc maybe if you can change it to something
like this COMMENTS_APP = 'zinnia_threaded_comments' will be more
clear. thanks and regards

2017-10-14 17:08 GMT-05:00, Julien Fache <notifications@github.com>:

**Comment by spotifysupport** [comment]
Thanks Reidelon, for this query as I had also faced a little problem in the beginning but when I used VPN then my was posted without showing any error. [Rocketmail Customer Service ](https://babasupport.org/email/rocketmail-customer-service-number/384)
